// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDId_UZsrYOk1lUPuWLmBePsqfXOXTi5Ag',
    appId: '1:251304224452:web:98bbf005061a7c2f234b91',
    messagingSenderId: '251304224452',
    projectId: 'home-736da',
    authDomain: 'home-736da.firebaseapp.com',
    storageBucket: 'home-736da.appspot.com',
    measurementId: 'G-74E3YF7QVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYvJ4tiwN-iAXGnD3UqLD5yUTYa-oQ0OM',
    appId: '1:251304224452:android:7790136438aa2cf3234b91',
    messagingSenderId: '251304224452',
    projectId: 'home-736da',
    storageBucket: 'home-736da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaEfoHlUkyLGdJsNBphJrtOcfBWovnV4k',
    appId: '1:251304224452:ios:632395927ca6caa0234b91',
    messagingSenderId: '251304224452',
    projectId: 'home-736da',
    storageBucket: 'home-736da.appspot.com',
    iosClientId: '251304224452-i0t5pf5sgh9jq44399uomcie1cok98fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.home',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaEfoHlUkyLGdJsNBphJrtOcfBWovnV4k',
    appId: '1:251304224452:ios:632395927ca6caa0234b91',
    messagingSenderId: '251304224452',
    projectId: 'home-736da',
    storageBucket: 'home-736da.appspot.com',
    iosClientId: '251304224452-i0t5pf5sgh9jq44399uomcie1cok98fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.home',
  );
}
