// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl9_pmooesPkH7XnzS6opCnJbohi5IloU',
    appId: '1:296370148746:web:229b9c9a0bcdd8e8cb2473',
    messagingSenderId: '296370148746',
    projectId: 'cars-82b51',
    authDomain: 'cars-82b51.firebaseapp.com',
    storageBucket: 'cars-82b51.appspot.com',
    measurementId: 'G-1DLDMXFGZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYgTQuLkShBndzaKOuiJjTvIC3PYLVyao',
    appId: '1:296370148746:android:f63b274386727b93cb2473',
    messagingSenderId: '296370148746',
    projectId: 'cars-82b51',
    storageBucket: 'cars-82b51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkvwdLeZN438SCVubaw1yfCitwofdAScg',
    appId: '1:296370148746:ios:717801c9691f85ffcb2473',
    messagingSenderId: '296370148746',
    projectId: 'cars-82b51',
    storageBucket: 'cars-82b51.appspot.com',
    iosClientId:
        '296370148746-vgi1r80ju04p1ndpts0mamkmsl8od09r.apps.googleusercontent.com',
    iosBundleId: 'com.example.home',
  );
}
